# Generated by Django 3.0.1 on 2019-12-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('logo', models.ImageField(default=True, upload_to='song_logo')),
                ('musicfile', models.FileField(upload_to='musicfile')),
            ],
        ),
    ]
