# Generated by Django 3.0.1 on 2019-12-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swag_music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
