# Generated by Django 3.0.1 on 2019-12-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swag_music', '0002_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.ImageField(default='song_logo/swaglogo1.jpg', upload_to='song_logo'),
        ),
    ]
